<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="nl" xml:lang="nl"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.280">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Statistiek met R - 8&nbsp; Chi-Kwadraat toets</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./driehoekstest.html" rel="next">
<link href="./f-toets.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "Geen resultaten",
    "search-matching-documents-text": "Gevonden documenten",
    "search-copy-link-title": "Kopieer link om te zoeken",
    "search-hide-matches-text": "Extra overeenkomsten verbergen",
    "search-more-match-text": "meer overeenkomst in dit document",
    "search-more-matches-text": "meer overeenkomsten in dit document",
    "search-clear-button-title": "Wissen",
    "search-detached-cancel-button-title": "Annuleren",
    "search-submit-button-title": "Verzenden"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Chi-Kwadraat toets</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Statistiek met R</a> 
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Inleiding</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./kansrekenen.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Kansrekening</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./kansverdelingen.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Kansverdelingen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./variabelen.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Variabelen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./toetsen.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Toetsen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./z-toets.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Z-Toets</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./t-toets.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">t-toets</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./f-toets.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">F-Toets</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chikwadraat.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Chi-Kwadraat toets</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./driehoekstest.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Driehoekstest</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./likelihood.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Maximum Likelihood</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Exploratieve Data Analyse (EDA)</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./datasplit.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Data splitsen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./kde.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Kernel Density Estimation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./referenties.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Referenties</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">Bijlagen</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./normale-verdeling.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Normale verdeling</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Inhoudsopgave</h2>
   
  <ul>
  <li><a href="#sec-chi-rsyntax" id="toc-sec-chi-rsyntax" class="nav-link active" data-scroll-target="#sec-chi-rsyntax"><span class="toc-section-number">8.1</span>  R Syntax</a></li>
  <li><a href="#sec-chi-aanpassing" id="toc-sec-chi-aanpassing" class="nav-link" data-scroll-target="#sec-chi-aanpassing"><span class="toc-section-number">8.2</span>  Aanpassingstoets</a></li>
  <li><a href="#sec-chi-onafhankelijkheid" id="toc-sec-chi-onafhankelijkheid" class="nav-link" data-scroll-target="#sec-chi-onafhankelijkheid"><span class="toc-section-number">8.3</span>  Onafhankelijkheidstoets</a></li>
  <li><a href="#sec-chi-homogeniteit" id="toc-sec-chi-homogeniteit" class="nav-link" data-scroll-target="#sec-chi-homogeniteit"><span class="toc-section-number">8.4</span>  Homogeniteitstoets</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-chikwadraat" class="quarto-section-identifier d-none d-lg-block"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Chi-Kwadraat toets</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>De Chi-kwadraattoets is een toets om na te gaan of twee of meer verdelingen van elkaar verschillen. De toets gaat na of de waargenomen aantallen systematisch afwijken van de verwachte aantallen en berekent daartoe het totaal van de gewogen kwadratische afwijkingen tussen deze aantallen. De chi-kwadraattoets vindt toepassing als</p>
<ul>
<li><em>aanpassingstoets</em> (Goodness of fit), waarbij getoetst wordt of de gevonden data passen bij een veronderstelde verdeling.</li>
<li><em>onafhankelijkheidstoets</em> (Independency), waarbij getoetst wordt of de simultane verdeling waaruit de data komen bestaat uit twee onafhankelijke.</li>
<li><em>homogeniteitstoets</em> (Homogeneity), waarbij getoetst wordt of verschillende steekproeven uit dezelfde verdeling afkomstig zijn.</li>
</ul>
<p>Toetsingsgrootheid: <span class="math inline">\(\chi^2 = \sum_{i=1}^{n} \frac{(O_i - E_i)^2}{E_i}\)</span> met</p>
<ul>
<li><span class="math inline">\(O_i\)</span> = waargenomen frequentie (observed)</li>
<li><span class="math inline">\(E_i\)</span> = verwachte frequentie volgens nulhypothes (Expected)</li>
</ul>
<p>Wanneer het verschil tussen de waargenomen frequenties en de verwachte frequenties klein is, kun je de nulhypothese niet verwerpen. Is het verschil groot dan kun je de nulhypothese verwerpen. De drempel tussen een klein en groot verschil is een waarde die afkomstig is van de Chi-kwadraatverdeling. Deze waarde, aangeduid als de kritische waarde, hangt af van het significantieniveau <span class="math inline">\(\alpha\)</span> (meestal ingesteld op 5%) en van de vrijheidsgraden.</p>
<section id="sec-chi-rsyntax" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="sec-chi-rsyntax"><span class="header-section-number">8.1</span> R Syntax</h2>
<p>De syntax van de <code>chisq.test()</code> functie is:</p>
<p><code>chisq.test(x, y = NULL, correct = TRUE, p = rep(1/length(x), length(x)), rescale.p = FALSE, simulate.p.value = FALSE, B = 2000)</code></p>
<p>Welke soort toets uitgevoerd wordt hangt van van de soort gegevens. Wanneer <code>x</code> een numerieke vector is of een 1-dimensionale tabel met numerieke waarden, dan wordt een aanpassingstoets uitgevoerd, waarbij de waarden van <code>x</code> opgevat worden als de waargenomen frequenties. Wanneer <code>x</code> een 2-dimensionale tabel, array of matrix is dan wordt dat gezien als een tabel van frequenties en wordt een test voor onafhankelijkheid uitgevoerd.</p>
<p>Een waarde voor <code>y</code> kan meestal genegeerd worden.</p>
<p><code>correct = TRUE</code> gebruiken wanneer een continuiteitscorrectie moet worden toegepast. Geef deze de waarde FALSE wanneer het niet wenselijk is.</p>
<p>Voor de aanpassingstoets maak <code>p</code> gelijk aan aan de onder de <span class="math inline">\(H_0\)</span> hypothese veronderstelde kansen voor elke categorie in vector <code>x</code>. De som hiervan moet exact gelijk zijn aan 1. Voor de onafhankelijkheidstoets is het argument <code>p</code> irrelevant omdat de verwachte frequenties berekend worden.</p>
</section>
<section id="sec-chi-aanpassing" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="sec-chi-aanpassing"><span class="header-section-number">8.2</span> Aanpassingstoets</h2>
<div id="exm-rozen" class="theorem example">
<p><span class="theorem-title"><strong>Voorbeeld 8.1 </strong></span><strong>Rozen</strong></p>
<p>Bij het kruisen van bepaalde soorten rode en witte rozen verkrijg je rode, witte en roze rozen. Volgens de theorie moet je deze in een verhouding krijgen van rood : wit : roze = 3:2:2. In een steekproef van gekruiste rozen zitten 35 rode, 31 witte en 14 roze rozen. Test met een chikwadraattoets (<span class="math inline">\(\alpha = 5\%\)</span>) of de theorie klopt. (Bron <a href="https://sites.williams.edu/bklingen/files/2012/02/R-code-for-inference-about-several-proportions.pdf">Klingenberg</a>)</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: theorie klopt, verdeling rood:wit:roze = 3:2:2</li>
<li><span class="math inline">\(H_1\)</span>: theorie klopt niet</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(<span class="fu">c</span>(<span class="dv">35</span>, <span class="dv">31</span>, <span class="dv">14</span>), <span class="at">p =</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">2</span>, <span class="dv">2</span>)<span class="sc">/</span><span class="dv">7</span>)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Chi-squared test for given probabilities

data:  c(35, 31, 14)
X-squared = 6.3479, df = 2, p-value = 0.04184</code></pre>
</div>
</div>
<p>Conclusie: De p-waarde van 0.04184 is kleiner dan <span class="math inline">\(\alpha\)</span>, dus <span class="math inline">\(H_0\)</span> afwijzen, er is voldoende bewijs dat de veronderstelde theoretische verhouding waarschijnlijk niet klopt.</p>
</div>
<div id="exm-dobbelsteen" class="theorem example">
<p><span class="theorem-title"><strong>Voorbeeld 8.2 </strong></span><strong>Dobbelsteen</strong></p>
<p>Iemand gooit 60 keer met een dobbelsteen en telt de ogenaantallen. Bij een zuivere dobbelsteen is de verwachting om elk van de ogenaantallen ongeveer 10 keer te gooien. Hij vindt als uitkomst voor de ogenaantallen 1 tot en met 6 resp. de waarden: 13, 9, 8, 11, 5, 14. Test met een chikwadraattoets (<span class="math inline">\(\alpha = 5\%\)</span>) of de dobbelsteen zuiver is. Bron: (<a href="https://nl.wikipedia.org/wiki/Chi-kwadraattoets">wikipedia</a>)</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: dobbelsteen is zuiver, kans voor elk ogenaantal is 1/6</li>
<li><span class="math inline">\(H_1\)</span>: dobbelsteen is niet zuiver</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(<span class="fu">c</span>(<span class="dv">13</span>, <span class="dv">9</span>, <span class="dv">8</span>, <span class="dv">11</span>, <span class="dv">5</span>, <span class="dv">14</span>), <span class="at">p =</span> <span class="fu">rep</span>(<span class="dv">1</span><span class="sc">/</span><span class="dv">6</span>, <span class="dv">6</span>))</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Chi-squared test for given probabilities

data:  c(13, 9, 8, 11, 5, 14)
X-squared = 5.6, df = 5, p-value = 0.3471</code></pre>
</div>
</div>
<p>Conclusie: De p-waarde van 0.3471 is veel groter dan <span class="math inline">\(\alpha\)</span>, dus <span class="math inline">\(H_0\)</span> accepteren, er is geen reden om aan de zuiverheid van de dobbelsteen te twijfelen.</p>
</div>
<div id="exm-boekomslag" class="theorem example">
<p><span class="theorem-title"><strong>Voorbeeld 8.3 </strong></span><strong>Boekomslag</strong></p>
<p>Bron: boek Buijs, voorbeeld 3, pag. 265-266</p>
<p>Een boek is verkocht met 4 verschillende omslagen (A, B, C en D). Verondersteld wordt dat van alle 4 soorten boeken evenveel exemplaren verkocht worden, dus een gelijkmatige verdeling. Bij een experiment met 200 verkochte boeken zijn de volgende resultaten gevonden.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>omslag <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">42</span>, <span class="dv">68</span>, <span class="dv">52</span>, <span class="dv">38</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">as.table</span>(omslag)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> A  B  C  D 
42 68 52 38 </code></pre>
</div>
</div>
<p>Toets de veronderstelling met <span class="math inline">\(\alpha = 5\%\)</span></p>
<ul>
<li><span class="math inline">\(H_0\)</span>: verkochte aantallen is voor elke omslag even groot</li>
<li><span class="math inline">\(H_1\)</span>: verkochte aantallen zijn per omslag verschillend</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(omslag , <span class="at">p =</span> <span class="fu">rep</span>(<span class="dv">1</span><span class="sc">/</span><span class="dv">4</span>, <span class="dv">4</span>))</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Chi-squared test for given probabilities

data:  omslag
X-squared = 10.72, df = 3, p-value = 0.01334</code></pre>
</div>
</div>
<p>Conclusie: De p-waarde van 0.01334 is kleiner dan <span class="math inline">\(\alpha\)</span>, dus <span class="math inline">\(H_0\)</span> afwijzen. De voorkeuren voor de omslagen zijn niet gelijk.</p>
</div>
<div id="exm-drukfouten" class="theorem example">
<p><span class="theorem-title"><strong>Voorbeeld 8.4 </strong></span><strong>Drukfouten</strong></p>
<p>Bron: boek Buijs, voorbeeld 4, pag. 267-268</p>
<p>In onderstaande tabel staat het aantal drukfouten per pagina in een boek van 150 pagina’s.</p>
<table class="table">
<thead>
<tr class="header">
<th>Aantal fouten (k) per pagina</th>
<th>0</th>
<th>1</th>
<th>2</th>
<th>3</th>
<th>4 of meer</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Aantal pagina’s met k drukfouten</td>
<td>60</td>
<td>50</td>
<td>25</td>
<td>10</td>
<td>5</td>
</tr>
</tbody>
</table>
<p>Ga met een chikwadraattoets na of het aantal drukfouten per pagina Poisson verdeeld is met <span class="math inline">\(\mu = 1\)</span>.</p>
<p>Definitie: <span class="math inline">\(\underline{k}\)</span> = aantal drukfouten per pagina.</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\underline{k}\)</span> is Poisson verdeeld met <span class="math inline">\(\mu = 1\)</span></li>
<li><span class="math inline">\(H_1\)</span>: <span class="math inline">\(\underline{k}\)</span> is NIET Poisson verdeeld met <span class="math inline">\(\mu = 1\)</span></li>
</ul>
<p>Eerst berekening van de kansen voor de verschillende waarden van k.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># aantal fouten per pagina</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>k <span class="ot">&lt;-</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">4</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="co"># theoretische frequenties volgens Poisson verdeling</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>prob <span class="ot">&lt;-</span> <span class="fu">dpois</span>(k,<span class="dv">1</span>)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="co"># correctie voor "4 fouten of meer",nu ook som alle probs = 1</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>prob[<span class="dv">5</span>] <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> <span class="fu">sum</span>(prob[<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>])</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>prob</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.36787944 0.36787944 0.18393972 0.06131324 0.01898816</code></pre>
</div>
</div>
<p>Nu kan de chikwadraattoets uitgevoerd worden.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>fouten <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">60</span>, <span class="dv">50</span>, <span class="dv">25</span>, <span class="dv">10</span>, <span class="dv">5</span>)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>toets <span class="ot">&lt;-</span> <span class="fu">chisq.test</span>(<span class="at">x =</span> fouten, <span class="at">p =</span> prob )</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>toets</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Chi-squared test for given probabilities

data:  fouten
X-squared = 2.8463, df = 4, p-value = 0.5839</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>toets<span class="sc">$</span>expected</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 55.181916 55.181916 27.590958  9.196986  2.848224</code></pre>
</div>
</div>
<p>De p-waarde is veel groter dan <span class="math inline">\(\alpha\)</span> dus <span class="math inline">\(H_0\)</span> wordt niet verworpen, het aantal drukfouten per pagina kan Poisson verdeeld zijn.</p>
<div class="info">
<p>De test geeft een waarschuwing “Chi-squared approximation may be incorrect” omdat er één of meerdere theoretische frequenties erg klein zijn. Een vuistregel is dat er geen theoretische frequenties kleiner dan 5 moeten zijn. Is dat wel het geval dan kun je eventueel klassen samenvoegen.</p>
<p>De laatste twee klassen worden nu samengevoegd waarna de chikwadraattoets opnieuw wordt uitgevoerd.</p>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># aantal fouten per pagina</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>k2 <span class="ot">&lt;-</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">3</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="co"># theoretische frequenties volgens Poisson verdeling</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>prob2 <span class="ot">&lt;-</span> <span class="fu">dpois</span>(k2,<span class="dv">1</span>)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="co"># correctie voor "3 fouten of meer",nu ook som alle probs = 1</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>prob2[<span class="dv">4</span>] <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> <span class="fu">sum</span>(prob2[<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>])</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>prob2</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3678794 0.3678794 0.1839397 0.0803014</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>fouten2 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">60</span>, <span class="dv">50</span>, <span class="dv">25</span>, <span class="dv">15</span>)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>toets2 <span class="ot">&lt;-</span> <span class="fu">chisq.test</span>(<span class="at">x =</span> fouten2, <span class="at">p =</span> prob2 )</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>toets2</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Chi-squared test for given probabilities

data:  fouten2
X-squared = 1.8754, df = 3, p-value = 0.5987</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>toets2<span class="sc">$</span>expected</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 55.18192 55.18192 27.59096 12.04521</code></pre>
</div>
</div>
</div>
</section>
<section id="sec-chi-onafhankelijkheid" class="level2" data-number="8.3">
<h2 data-number="8.3" class="anchored" data-anchor-id="sec-chi-onafhankelijkheid"><span class="header-section-number">8.3</span> Onafhankelijkheidstoets</h2>
<p>De chi-kwadraattoets voor onafhankelijkheid test of twee <em>kwalitatieve</em> variabelen onafhankelijk zijn, of er dus een relatie bestaat tussen twee categoriale variabelen.</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: de variabelen zijn onafhankelijk, er is geen relatie tussen de twee categoriale variabelen.</li>
<li><span class="math inline">\(H_1\)</span>: de variabelen zijn afhankelijk, er is een relatie tussen de twee categoriale variabelen.</li>
</ul>
<p>LET OP: Deze toets kan alleen gedaan worden wanneer de verwachte frequenties in alle groepen groter of gelijk aan 5 zijn.</p>
<div id="exm-haarkleur-oogkleur" class="theorem example">
<p><span class="theorem-title"><strong>Voorbeeld 8.5 </strong></span><strong>Haarkleur-Oogkleur relatie</strong></p>
<p>In een steekproef van 65 studenten is de haarkleur (categorieën blond, bruin, donker) en oogkleur (categorieën licht, donker) vastgelegd. De onderstaande tabel vat de tellingen samen. (Bron <a href="https://sites.williams.edu/bklingen/files/2012/02/R-code-for-inference-about-several-proportions.pdf">Klingenberg</a>)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>kleuren <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">12</span>, <span class="dv">2</span>, <span class="dv">8</span>, <span class="dv">25</span>, <span class="dv">6</span>, <span class="dv">12</span>), <span class="at">ncol =</span> <span class="dv">3</span>)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(kleuren) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"blond"</span>, <span class="st">"bruin"</span>, <span class="st">"zwart"</span>)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(kleuren) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"licht"</span>, <span class="st">"donker"</span>)</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>kleuren</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       blond bruin zwart
licht     12     8     6
donker     2    25    12</code></pre>
</div>
</div>
<p>Test met een chikwadraattoets(<span class="math inline">\(\alpha = 5\%\)</span>) of haarkleur en oogkleur met elkaar geassocieerd zijn.</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: haarkleur en oogkleur zijn onafhankelijk van elkaar</li>
<li><span class="math inline">\(H_1\)</span>: haarkleur en oogkleur zijn met elkaar verbonden</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span> <span class="fu">chisq.test</span>(kleuren)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>test</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  kleuren
X-squared = 15.938, df = 2, p-value = 0.000346</code></pre>
</div>
</div>
<p>Je kunt de verschillende waarden ook afzonderlijk opvragen:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>test<span class="sc">$</span>method    <span class="co"># toetsingsmethode</span></span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Pearson's Chi-squared test"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>test<span class="sc">$</span>statistic <span class="co"># chikwadraat waarde</span></span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>X-squared 
 15.93795 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>test<span class="sc">$</span>p.value   <span class="co"># p-waarde</span></span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0003460333</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>test<span class="sc">$</span>parameter <span class="co"># aantal vrijheidsgraden</span></span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>df 
 2 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>test<span class="sc">$</span>observed  <span class="co"># waargenomen frequenties</span></span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       blond bruin zwart
licht     12     8     6
donker     2    25    12</code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>test<span class="sc">$</span>expected  <span class="co"># verwachte frequenties</span></span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       blond bruin zwart
licht    5.6  13.2   7.2
donker   8.4  19.8  10.8</code></pre>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>test<span class="sc">$</span>residuals <span class="co"># residuen, (observed - expected) / sqrt(expected).</span></span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           blond     bruin      zwart
licht   2.704494 -1.431253 -0.4472136
donker -2.208210  1.168613  0.3651484</code></pre>
</div>
</div>
<p>Conclusie: De p-waarde van 0.000346 is veel kleiner dan <span class="math inline">\(\alpha\)</span>, dus <span class="math inline">\(H_0\)</span> afwijzen, er is een significante relatie tussen haarkleur en oogkleur.</p>
</div>
<div id="exm-betaalgedrag-leeftijd" class="theorem example">
<p><span class="theorem-title"><strong>Voorbeeld 8.6 </strong></span><strong>Betaalgedrag en leeftijd</strong></p>
<p>Bron: boek Buijs, voorbeeld 6, pag. 272-273</p>
<p>Een bank onderzoekt van 100 verstrekte leningen hoe de aflossingen zijn verlopen. De bank wil onderzoeken of het betaalgedrag afhangt van de leeftijd van de leners.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>afbetaling <span class="ot">&lt;-</span> <span class="fu">rbind</span>(<span class="fu">c</span>(<span class="dv">24</span>, <span class="dv">36</span>), <span class="fu">c</span>(<span class="dv">6</span>, <span class="dv">34</span>))</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dimnames</span>(afbetaling) <span class="ot">=</span> <span class="fu">list</span>(<span class="at">Leeftijd =</span> <span class="fu">c</span>(<span class="st">"jonger dan 40"</span>, <span class="st">"40 of ouder"</span>), </span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>                            <span class="at">Betaalgedrag =</span> <span class="fu">c</span>(<span class="st">"Wanbetalers"</span>, <span class="st">"Correct"</span>))</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>afbetaling</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               Betaalgedrag
Leeftijd        Wanbetalers Correct
  jonger dan 40          24      36
  40 of ouder             6      34</code></pre>
</div>
</div>
<p>Met rij- en kolomsommen:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">addmargins</span>(afbetaling)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               Betaalgedrag
Leeftijd        Wanbetalers Correct Sum
  jonger dan 40          24      36  60
  40 of ouder             6      34  40
  Sum                    30      70 100</code></pre>
</div>
</div>
<p>En weergegeven als fracties:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.table</span>(afbetaling)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               Betaalgedrag
Leeftijd        Wanbetalers Correct
  jonger dan 40        0.24    0.36
  40 of ouder          0.06    0.34</code></pre>
</div>
</div>
<p>Hypothesen:</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: Er is onafhankelijkheid, betaalgedrag hangt niet af van leeftijd</li>
<li><span class="math inline">\(H_1\)</span>: Er is geen onafhankelijkheid, betaalgedrag hangt af van leeftijd</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(afbetaling, <span class="at">correct =</span> <span class="cn">FALSE</span>)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  afbetaling
X-squared = 7.1429, df = 1, p-value = 0.007526</code></pre>
</div>
</div>
<p>De berekende p-waarde is kleiner dan <span class="math inline">\(\alpha = 0.05\)</span> dus <span class="math inline">\(H_0\)</span> wordt verworpen, het betaalgedrag hangt wel af van de leeftijd.</p>
</div>
<div id="exm-kiesgedrag" class="theorem example">
<p><span class="theorem-title"><strong>Voorbeeld 8.7 </strong></span><strong>Kiesgedrag Mannen-Vrouwen</strong></p>
<p>Bron: boek Buijs, voorbeeld 7, pag. 274-275</p>
<p>Onderzoek naar de voorkeur voor een politieke partij onder mannen en vrouwen, totaal 1000 personen.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>partijvoorkeur <span class="ot">&lt;-</span> <span class="fu">rbind</span>(<span class="fu">c</span>(<span class="dv">170</span>, <span class="dv">230</span>), <span class="fu">c</span>(<span class="dv">210</span>, <span class="dv">190</span>), <span class="fu">c</span>(<span class="dv">120</span>, <span class="dv">80</span>))</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dimnames</span>(partijvoorkeur) <span class="ot">=</span> <span class="fu">list</span>(<span class="at">Partij =</span> <span class="fu">c</span>(<span class="st">"CDA"</span>, <span class="st">"PvdA"</span>, <span class="st">"VVD"</span>), <span class="at">Geslacht =</span> <span class="fu">c</span>(<span class="st">"man"</span>,<span class="st">"vrouw"</span>))</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a><span class="fu">addmargins</span>(partijvoorkeur)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Geslacht
Partij man vrouw  Sum
  CDA  170   230  400
  PvdA 210   190  400
  VVD  120    80  200
  Sum  500   500 1000</code></pre>
</div>
</div>
<p>De tabel geeft een bepaald verschil te zien in de voorkeuren van mannen en vrouwen. Dat is nog beter te zien wanneer naar de fracties gekeken wordt:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.table</span>(partijvoorkeur)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Geslacht
Partij  man vrouw
  CDA  0.17  0.23
  PvdA 0.21  0.19
  VVD  0.12  0.08</code></pre>
</div>
</div>
<p>Hypothesen:</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: Er is geen verschil in voorkeuren van man en vrouw</li>
<li><span class="math inline">\(H_1\)</span>: Er is wel verschil in voorkeuren van man en vrouw</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(partijvoorkeur, <span class="at">correct =</span> <span class="cn">FALSE</span>)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  partijvoorkeur
X-squared = 18, df = 2, p-value = 0.0001234</code></pre>
</div>
</div>
<p>De berekende p-waarde is kleiner dan <span class="math inline">\(\alpha = 0.05\)</span> dus <span class="math inline">\(H_0\)</span> wordt verworpen, er is verschil in partijvoorkeur tussen mannen en vrouwen.</p>
</div>
<div id="exm-medicijntest" class="theorem example">
<p><span class="theorem-title"><strong>Voorbeeld 8.8 </strong></span><strong>Medicijntest</strong></p>
<p>Om de effectiviteit van een geneesmiddel te testen worden 105 patienten in twee groep verdeeld. Een groep van 50 patienten wordt met het medicijn behandeld en de resterende 55 patienten is een controlegroep. Na twee weken wordt de conditie van alle patienten onderzocht en vastgesteld of er al dan niet een verbetering is opgetreden. De resultaten zijn in de volgende tabel te zien.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/medicijntest.csv"</span>)</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(df<span class="sc">$</span>behandeling, df<span class="sc">$</span>verbetering)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                
                 niet-verbeterd verbeterd
  behandeld                  15        35
  niet-behandeld             29        26</code></pre>
</div>
</div>
<p>Hypothesen:</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: Behandeling met het medicijn geeft geen verbetering</li>
<li><span class="math inline">\(H_1\)</span>: Behandeling met het medicijn geeft wel verbetering</li>
</ul>
<p>Test de hypothesen met een chikwadraattoets(<span class="math inline">\(\alpha = 5\%\)</span>). De twee vectoren worden als input voor de functie gebruikt. Ook wordt het argument <code>correct = FALSE</code> opgenomenom de continuiteitscorrectie volgens Yates uit te schakelen.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(df<span class="sc">$</span>behandeling, df<span class="sc">$</span>verbetering, <span class="at">correct =</span> <span class="cn">FALSE</span>)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  df$behandeling and df$verbetering
X-squared = 5.5569, df = 1, p-value = 0.01841</code></pre>
</div>
</div>
<p>Conclusie: De p-waarde van 0,01841 is kleiner dan <span class="math inline">\(\alpha\)</span>, dus <span class="math inline">\(H_0\)</span> afwijzen, er is dus voldoende bewijs om te veronderstellen dat behandeling met het medicijn een verbetering geeft.</p>
</div>
</section>
<section id="sec-chi-homogeniteit" class="level2" data-number="8.4">
<h2 data-number="8.4" class="anchored" data-anchor-id="sec-chi-homogeniteit"><span class="header-section-number">8.4</span> Homogeniteitstoets</h2>
<p>Vergelijk proporties over twee groepen</p>
<div id="exm-ontbijtei" class="theorem example">
<p><span class="theorem-title"><strong>Voorbeeld 8.9 </strong></span><strong>Voorkeur Ontbijtei</strong></p>
<p>Aan een groep van 25 vrouwen en een groep van 17 mannen is gevraagd hoe ze het liefst hun ei op zondagmorgen willen hebben: Gebakken, Gekookt of Roerei. De gegevens zijn samengevat in onderstaande tabel.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>eitje <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">5</span>, <span class="dv">9</span>, <span class="dv">12</span>, <span class="dv">3</span>, <span class="dv">7</span>, <span class="dv">5</span>), <span class="at">ncol =</span> <span class="dv">3</span>)</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(eitje) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Gebakken"</span>, <span class="st">"Gekookt"</span>, <span class="st">"Roerei"</span>)</span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(eitje) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Vrouwen"</span>, <span class="st">"Mannen"</span>)</span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>eitje</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        Gebakken Gekookt Roerei
Vrouwen        5      12      7
Mannen         9       3      5</code></pre>
</div>
</div>
<p>Test met een chikwadraattoets(<span class="math inline">\(\alpha = 5\%\)</span>) of de voorkeuren gelijk verdeeld zijn voor mannen en vrouwen, dus of de verhoudingen homogeen zijn over beide groepen?</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: de verdelingen zijn voor mannen en vrouwen hetzelfde</li>
<li><span class="math inline">\(H_1\)</span>: de verdelingen zijn voor mannen en vrouwen verschillend</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span> <span class="fu">chisq.test</span>(eitje)</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>test</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  eitje
X-squared = 5.8516, df = 2, p-value = 0.05362</code></pre>
</div>
</div>
<p>Omdat de aantallen klein zijn verschijnt er een waarschuwing dat de berekende waarden niet juist kunnen zijn. Een van de verwachte waarden is kleiner dan 5.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>test<span class="sc">$</span>expected</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        Gebakken  Gekookt  Roerei
Vrouwen 8.195122 8.780488 7.02439
Mannen  5.804878 6.219512 4.97561</code></pre>
</div>
</div>
<p>Je kunt in deze test de p-waarden simuleren waardoor het resultaat iets betrouwbaarder wordt.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(eitje, <span class="at">simulate.p.value =</span> <span class="cn">TRUE</span>, <span class="at">B =</span> <span class="dv">10000</span>)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test with simulated p-value (based on 10000
    replicates)

data:  eitje
X-squared = 5.8516, df = NA, p-value = 0.05769</code></pre>
</div>
</div>
<p>Conclusie: De p-waarde is iets groter dan <span class="math inline">\(\alpa\)</span>, dus <span class="math inline">\(H_0\)</span> accepteren, er is niet voldoende bewijs om te concluderen dat de verdelingen bij mannen en vrouwen verschillend is.</p>
<p>Tip: Een andere mogelijkheid is om <code>fisher.test()</code> te gebruiken.</p>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Gekopieerd!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Gekopieerd!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
    var links = window.document.querySelectorAll('a:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
          // target, if specified
          link.setAttribute("target", "_blank");
          // default icon
          link.classList.add("external");
      }
    }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./f-toets.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">F-Toets</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./driehoekstest.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Driehoekstest</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>