<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="nl" xml:lang="nl"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.280">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Statistiek met R - 6&nbsp; t-toets</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./f-toets.html" rel="next">
<link href="./z-toets.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "Geen resultaten",
    "search-matching-documents-text": "Gevonden documenten",
    "search-copy-link-title": "Kopieer link om te zoeken",
    "search-hide-matches-text": "Extra overeenkomsten verbergen",
    "search-more-match-text": "meer overeenkomst in dit document",
    "search-more-matches-text": "meer overeenkomsten in dit document",
    "search-clear-button-title": "Wissen",
    "search-detached-cancel-button-title": "Annuleren",
    "search-submit-button-title": "Verzenden"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">t-toets</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Statistiek met R</a> 
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Inleiding</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./kansrekenen.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Kansrekening</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./kansverdelingen.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Kansverdelingen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./variabelen.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Variabelen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./toetsen.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Toetsen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./z-toets.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Z-Toets</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./t-toets.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">t-toets</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./f-toets.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">F-Toets</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chikwadraat.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Chi-Kwadraat toets</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./driehoekstest.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Driehoekstest</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./likelihood.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Maximum Likelihood</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Exploratieve Data Analyse (EDA)</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./datasplit.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Data splitsen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./kde.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Kernel Density Estimation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./referenties.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Referenties</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">Bijlagen</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./normale-verdeling.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Normale verdeling</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Inhoudsopgave</h2>
   
  <ul>
  <li><a href="#sec-ttoets-1" id="toc-sec-ttoets-1" class="nav-link active" data-scroll-target="#sec-ttoets-1"><span class="toc-section-number">6.1</span>  t-toets voor 1 steekproef</a></li>
  <li><a href="#sec-ttoets-2-onafhankelijk" id="toc-sec-ttoets-2-onafhankelijk" class="nav-link" data-scroll-target="#sec-ttoets-2-onafhankelijk"><span class="toc-section-number">6.2</span>  t-toets voor twee onafhankelijke steekproeven</a>
  <ul class="collapse">
  <li><a href="#sec-ttoets-2-onafh-stapeling" id="toc-sec-ttoets-2-onafh-stapeling" class="nav-link" data-scroll-target="#sec-ttoets-2-onafh-stapeling"><span class="toc-section-number">6.2.1</span>  Stapeling</a></li>
  </ul></li>
  <li><a href="#sec-ttoets-2-gepaard" id="toc-sec-ttoets-2-gepaard" class="nav-link" data-scroll-target="#sec-ttoets-2-gepaard"><span class="toc-section-number">6.3</span>  t-toets voor twee gepaarde steekproeven</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-ttoets" class="quarto-section-identifier d-none d-lg-block"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">t-toets</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>De t-toets, ook wel Student toets geheten, wordt gebruikt om hypotheses over het gemiddelde van een populatie of twee populaties te toetsen. De t-verdeling zit dicht tegen de normale verdeling aan en wordt bij een kleine steekproef (30 of minder waarnemingen) uit een normale verdeling met onbekende <span class="math inline">\(\sigma\)</span> gebruikt. Wanneer de steekproef groot genoeg is (n &gt; 30) kan de t-toets ook gebruikt worden wanneer de data niet normaal verdeeld is (volgens centrale limietstelling).</p>
<p>Er zijn drie soorten t-toetsen:</p>
<ol type="1">
<li><p><strong>t-toets voor één steekproef</strong> - Als toets voor de nulhypothese dat het gemiddelde van een normaal verdeelde populatie gelijk is an een bepaalde vooraf gespecificeerde waarde <span class="math inline">\(\mu_0\)</span>.</p></li>
<li><p><strong>t-toets voor twee onafhankelijke steekproeven</strong> - Als toets voor de nulhypothese dat de gemiddelden van twee normaal verdeelde populaties aan elkaar gelijk zijn.</p></li>
<li><p><strong>t-toets voor twee gepaarde steekproeven</strong> De gemiddeldes van twee gepaarde steekproeven met elkaar vergelijken. Bij gepaarde steekproeven correspondeert een waarde in de ene steekproef met een bepaalde waarde in de andere steekproef. Hierbij gaat <span class="math inline">\(H_0\)</span> er vanuit dat de twee gemiddeldes hetzelfde zijn en de alternatieve hypothese dat dit niet het geval is.</p></li>
</ol>
<p>Syntax: <code>t.test(x, ...)</code></p>
<p>Argumenten:</p>
<ul>
<li><code>x</code>: numerieke vector met waarnemingen</li>
<li><code>y</code>: numerieke vector met waarnemingen (optioneel)</li>
<li><code>alternative</code>: tekst die de alternatieve hypothese specificeert, keuzes “two.sided” (default), “less”, “greater”</li>
<li><code>mu</code>: getal dat de werkelijke waarde van het gemiddelde aangeeft (of verschil in gemiddelden bij een test met twee steekproeven).</li>
<li><code>paired</code>: logische aanduiding of je een gepaarde t-toets wilt, <code>FALSE</code> (default) of <code>TRUE</code> (dan zowel x als y specificeren).</li>
<li><code>var.equal</code>: logische aanduiding of de twee varianties als gelijk moeten worden behandeld, <code>FALSE</code> (default) of <code>TRUE</code>.</li>
<li><code>conf.level = 0.95</code>, getal voor het betrouwbaarheidsinterval, defaultwaarde <code>0.95</code></li>
<li><code>formula</code>: een formule (optioneel)</li>
</ul>
<section id="sec-ttoets-1" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="sec-ttoets-1"><span class="header-section-number">6.1</span> t-toets voor 1 steekproef</h2>
<div id="exm-ttoets-1" class="theorem example">
<p><span class="theorem-title"><strong>Voorbeeld 6.1 </strong></span>Een bedrijf stelt dat gemiddeld hoogstens 200 vervuilingseenheden (VE’s) per dag geloosd worden. De resultaten van een controle op 10 willekeurige dagen zijn: 190, 250, 320, 410, 310, 280, 230, 370, 350, 290. Toets of het bedrijf gelijk heeft met <span class="math inline">\(\alpha = 0.01\)</span>.</p>
<p>(Bron: boek Buijs, hfst. 9, voorbeeld 11)</p>
<p>De hypothesen worden als volgt geformuleerd:</p>
<ul>
<li><span class="math inline">\(H_0: \mu \le 200\)</span></li>
<li><span class="math inline">\(H_1: \mu \gt 200\)</span> (Dus een rechts eenzijdige toetsing)</li>
</ul>
<p>Toetsingsgrootheid <span class="math inline">\(\bar{x}\)</span> : het steekproefgemiddelde</p>
<p><span class="math inline">\(\bar{x} \sim t\)</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>ve <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">190</span>, <span class="dv">250</span>, <span class="dv">320</span>, <span class="dv">410</span>, <span class="dv">310</span>, <span class="dv">280</span>, <span class="dv">230</span>, <span class="dv">370</span>, <span class="dv">350</span>, <span class="dv">290</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(<span class="at">x =</span> ve, <span class="at">mu =</span> <span class="dv">200</span>, <span class="at">alternative =</span> <span class="fu">c</span>(<span class="st">"greater"</span>), <span class="at">conf.level =</span> <span class="fl">0.99</span>)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  ve
t = 4.7434, df = 9, p-value = 0.0005269
alternative hypothesis: true mean is greater than 200
99 percent confidence interval:
 240.5189      Inf
sample estimates:
mean of x 
      300 </code></pre>
</div>
</div>
<p>De berekende t-waarde 4.74 heeft een p-waarde van 0.0005. Deze is kleiner dan <span class="math inline">\(\alpha\)</span> dus <span class="math inline">\(H_0\)</span> wordt verworpen, het bedrijf heeft geen gelijk.</p>
</div>
<div id="exm-ttoets-2" class="theorem example">
<p><span class="theorem-title"><strong>Voorbeeld 6.2 </strong></span>Een vulmachine vult flessen met 500 ml vruchtensap. Het vulvolume volgt een normale verdelingt. Om te onderzoeken of de machine de flessen met een te laag volume afvult, wordt een steekproef van 20 flessen onderzocht. De waarnemingen staan in het bestand <code>bottles.csv</code>.</p>
<p>(Bron: boek “using R for Statistics”, Sarah Stowell, chapter 10)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>bottles <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="at">file =</span> <span class="st">"data/bottles.csv"</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(bottles<span class="sc">$</span>Volume)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 491.5705</code></pre>
</div>
</div>
<p>Het gevonden gemiddelde is inderdaad minder dan 500. Dit kan toeval zijn. Toets daarom met een t-test of het gemiddelde significant minder dan 500 is en <span class="math inline">\(\alpha = 0.01\)</span>.</p>
<ul>
<li><span class="math inline">\(H_0 : \mu = 500\)</span></li>
<li><span class="math inline">\(H_1 : \mu \lt 500\)</span> (Dit is dus een links eenzijdige toetsing)</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(<span class="at">x =</span> bottles<span class="sc">$</span>Volume, <span class="at">mu =</span> <span class="dv">500</span>, <span class="at">alternative =</span> <span class="st">"less"</span>, <span class="at">conf.level =</span> <span class="fl">0.99</span>)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  bottles$Volume
t = -1.5205, df = 19, p-value = 0.07243
alternative hypothesis: true mean is less than 500
99 percent confidence interval:
     -Inf 505.6495
sample estimates:
mean of x 
 491.5705 </code></pre>
</div>
</div>
<p>Voor het eenzijdige betrouwbaarheidsinterval geldt dat het gemiddelde volume minder is dan 505.65.</p>
<p>De p-waarde is groter dan het significantieniveau van 0.01, de nulhypothese kan niet verworpen worden. Er is dus geen bewijs dat het gemiddelde vulvolume minder dan 500 ml is.</p>
</div>
</section>
<section id="sec-ttoets-2-onafhankelijk" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="sec-ttoets-2-onafhankelijk"><span class="header-section-number">6.2</span> t-toets voor twee onafhankelijke steekproeven</h2>
<p>Dit is de meest gebruikte t-toets. Hierbij worden de gemiddelden van twee willekeurige steekproeven met elkaar vergeleken. Naast onafhankelijkheid wordt aangenomen dat beide steekproeven uit normale verdelingen zijn gehaald waarvan de populatiegemiddelden en varianties onbekend zijn.</p>
<p>Een typisch voorbeeld is bijvoorbeeld de concentratie van een medicijn in het bloed van twee verschillende groepen. En je zou graag willen weten of het waarschijnlijk is dat deze twee groepen verschillen met betrekking tot deze variabele.</p>
<ul>
<li><span class="math inline">\(H_0 : \mu_1 = \mu_2\)</span> - De populatiegemiddelden zijn gelijk.</li>
<li><span class="math inline">\(H_1 : \mu_1 \ne \mu_2\)</span> - De populatiegemiddelden zijn niet gelijk (tweezijdige toetsing)</li>
</ul>
<p>De formele toetsing van de nulhypothese doet de volgende aannames:</p>
<ol type="1">
<li><span class="math inline">\(H_0\)</span> is waar.</li>
<li>De onderzochte groepen zijn onafhankelijk (hebben geen overlap).</li>
<li>De gegevens zijn normaal verdeeld.</li>
<li>De varianties van de twee steekproeven zijn gelijk.</li>
</ol>
<p>Alle bovenstaande aannames moeten kloppen, of redelijk dicht in de buurt komen om de test een nauwkeurig resultaat te geven.</p>
<ul>
<li>Aanname 1 is natuurlijk belangrijk, maar zit ingebakken in de toetsingsprocedure.</li>
<li>Aanname 2 is vanuit het oogpunt van de statistische praktijk fundamenteel.</li>
<li>Aanname 3. is erg belangrijk, maar het is relatief eenvoudig te controleren.</li>
<li>Wannneer aanname 4 niet klopt zijn er andere tests en oplossingen voor deze situaties, zoals een Welch’s t-toets (Satterthwaite ).</li>
</ul>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Opmerking
</div>
</div>
<div class="callout-body-container callout-body">
<p>Wanneer de gegevens niet normaal verdeeld zijn of er zijn serieuze uitschieters, dan is een Mann-Whitney U test het beste alternatief.</p>
</div>
</div>
<div id="exm-ttoets-3" class="theorem example">
<p><span class="theorem-title"><strong>Voorbeeld 6.3 </strong></span>Om te onderzoeken of vrouwen van 40 jaar gemiddeld zwaarder zijn dan vrouwen van 30 jaar wordt uit beide groepen een aselecte steekproef genomen van 20 personen. getoetst wordt met <span class="math inline">\(\alpha = 0.05\)</span>.</p>
<p>(Inspiratiebron: <a href="https://nl.wikipedia.org/wiki/T-toets" class="uri">https://nl.wikipedia.org/wiki/T-toets</a>)</p>
<p>In dit voorbeeld worden de data gesimuleerd.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># simulatie data</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">234</span>)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>v30 <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">rnorm</span>(<span class="at">n=</span><span class="dv">20</span>, <span class="at">mean=</span><span class="dv">69</span>, <span class="at">sd=</span> <span class="fl">16.0</span>), <span class="dv">0</span>) <span class="co"># groep vrouwen 30 jaar</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>v40 <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">rnorm</span>(<span class="at">n=</span><span class="dv">20</span>, <span class="at">mean=</span><span class="dv">73</span>, <span class="at">sd=</span> <span class="fl">14.6</span>), <span class="dv">0</span>) <span class="co"># groep vrouwen 40 jaar</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(v30); <span class="fu">mean</span>(v40)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 67.7</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 71.45</code></pre>
</div>
</div>
<p>Nu de t-toets</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(<span class="at">x=</span>v30, <span class="at">y=</span>v40)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  v30 and v40
t = -0.74441, df = 33.52, p-value = 0.4618
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 -13.992892   6.492892
sample estimates:
mean of x mean of y 
    67.70     71.45 </code></pre>
</div>
</div>
<p><span class="math inline">\(p\)</span> is groter dan <span class="math inline">\(\alpha\)</span>, de nulhypothese wordt niet verworpen. Weliswaar waren de vrouwen van 40 in de steekproef gemiddeld 3.75 kg zwaarder dan de vrouwen van 30, maar dit verschil is niet significant gezien de spreiding binnen de groepen.</p>
</div>
<section id="sec-ttoets-2-onafh-stapeling" class="level3" data-number="6.2.1">
<h3 data-number="6.2.1" class="anchored" data-anchor-id="sec-ttoets-2-onafh-stapeling"><span class="header-section-number">6.2.1</span> Stapeling</h3>
<p>Bij een <code>t.test</code> voor twee steekproeven kunnen de gegevens zowel in gestapelde als ongestapelde vorm aanwezig zijn. De gegevens zijn in gestapelde vorm wanneer er een variabele is voor de waarden en een andere variabele voor de categorieën. De gegevens zijn in ongestapelde vorm wanneer de waarden voor elke elke steekproef in een afzonderlijke variabele zitten, de vorm van een kruistabel. Zie het voorbeeld in de volgende afbeelding.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/stapeling.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Figuur: gestapelde en ongestapelde gegevens</figcaption><p></p>
</figure>
</div>
<p><strong>gestapelde vorm</strong></p>
<p><code>t.test(waarde~groep, dataset)</code></p>
<p>Hierbij is <code>waarde</code> de variabelenaam voor de waarden en <code>groep</code> de variabelenaam voor de namen van de groepen.</p>
<p>Wanneer de variabele voor de groepen meer dan twee niveaus bevat moet aangegeven worden welke twee groepen met elkaar vergeleken moeten worden, bijvoorbeeld: <code>t.test(waarde~groep, dataset, groep %in% c("groep1", "groep2"))</code></p>
<p><strong>ongestapelde vorm</strong></p>
<p><code>t.test(dataset$groep1, dataset$groep2)</code></p>
<p>Standaard gaat R er van uit dat de varianties voor de twee steekproeven verschillend zijn. Is de veronderstelling dat deze varianties wel gelijk zijn, dan kan dat aangegeven worden met het argument <code>var.equal=TRUE</code>. Er wordt dan een variantieschatting van de samengevoegde gegevens gemaakt. Of de varianties wel/niet gelijk zijn kan weer getoetst worden met de <strong>F-toets</strong>.</p>
<p>Ook kan bij de t-test voor twee onafhankelijke steekproeven een eenzijdige toetsing via het <code>alternative</code> argument worden gespecificeerd. Bij <code>alternative = "greater"</code> is de alternatieve hypothese dat het gemiddelde voor de eerste groep groter is dan het gemiddelde voor de tweede groep. Analoog voor de waarde “less”. Bij het gebruik van gestapelde gegevens moet je via de functie <code>levels</code> eerst bepalen welke de eerste en welke de tweede groep is.</p>
<div id="exm-ttoets-4" class="theorem example">
<p><span class="theorem-title"><strong>Voorbeeld 6.4 </strong></span>De dataset <code>iris</code> welke standaard in R be zit, bevat voor elk van de soorten <em>setosa</em>, <em>versicolor</em> en <em>virginica</em> steeds 50 waarnemingen in centimeters van de variabelen <code>Sepal.Length</code>, <code>Sepal.Width</code>, <code>Petal.length</code> en <code>Petal.Width</code>. (sepal = kelkblad, petal = bloemblad).</p>
<p>Voer een <code>t.test</code> uit om te bepalen of er een significant verschil is in de gemiddelde <code>Sepal.Width</code> voor de soorten <code>versicolor</code> en <code>virginica</code>. Ga er hierbij vanuit dat <code>Sepal.Width</code> normaal verdeeld is en dat de variantie voor de twee groepen gelijk is.</p>
<p>(Bron: boek “using R for Statistics”, Sarah Stowell, chapter 10)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(iris)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   150 obs. of  5 variables:
 $ Sepal.Length: num  5.1 4.9 4.7 4.6 5 5.4 4.6 5 4.4 4.9 ...
 $ Sepal.Width : num  3.5 3 3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 ...
 $ Petal.Length: num  1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 ...
 $ Petal.Width : num  0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1 ...
 $ Species     : Factor w/ 3 levels "setosa","versicolor",..: 1 1 1 1 1 1 1 1 1 1 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(iris<span class="sc">$</span>Species)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "setosa"     "versicolor" "virginica" </code></pre>
</div>
</div>
<p>Er zijn 150 records, 50 voor elke soort. De gegevens zijn in gestapelde vorm. De groep versicolor komt voor groep virginica.</p>
<p><strong>Toetsingsgrootheid</strong> : <span class="math inline">\(v\)</span> = gemiddelde Sepal.Width versicolor - gemiddelde Sepal.Width virginica</p>
<p><span class="math inline">\(H_0 : v = 0\)</span></p>
<p><span class="math inline">\(H_1 : v \neq 0\)</span>:</p>
<p>De t-toets:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(Sepal.Width<span class="sc">~</span>Species, iris, Species <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"versicolor"</span>, <span class="st">"virginica"</span>), <span class="at">var.equal =</span> <span class="cn">TRUE</span>)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Two Sample t-test

data:  Sepal.Width by Species
t = -3.2058, df = 98, p-value = 0.001819
alternative hypothesis: true difference in means between group versicolor and group virginica is not equal to 0
95 percent confidence interval:
 -0.33028246 -0.07771754
sample estimates:
mean in group versicolor  mean in group virginica 
                   2.770                    2.974 </code></pre>
</div>
</div>
<p>Het 95% betrouwbaarheidsinterval voor het verschil loopt van -0.330 tot -0.078 wat inhoudt dat het gemiddelde van Sepal.Width voor versicolor tussen de 0.078 en 0.330 centimeter minder is dan voor virinica. De p-waarde van 0.001819 is kleiner dan <span class="math inline">\(\alpha\)</span> = 0.05. Dus <span class="math inline">\(H_0\)</span> wordt afgewezen, dus het gemiddelde Sepal.Width is voor de soorten versicolor en virginica niet gelijk.</p>
</div>
</section>
</section>
<section id="sec-ttoets-2-gepaard" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="sec-ttoets-2-gepaard"><span class="header-section-number">6.3</span> t-toets voor twee gepaarde steekproeven</h2>
<p>Een gepaarde t.test kan uitgevoerd worden via het argument <code>paired = TRUE</code>. De gegevens moeten hetzelfde aantal waarnemingen voor elke groep hebben, zodat er een 1-op-1 relatie tussen de waarnemingen in elke groep is. Voor de rest is de werkwijze gelijk aan de t-toets voor twee onafhankelijke steekproeven.</p>
<div id="exm-ttoets-5" class="theorem example">
<p><span class="theorem-title"><strong>Voorbeeld 6.5 </strong></span>Het bestand <code>brains.csv</code> bevat het hersenvolume van tien eeneiige tweelingen in cm<sup>3</sup>, zowel van van de eerstgeborene (<code>Twin1</code>) als van de laatst geborene (<code>Twin2</code>).</p>
<p>(Bron: boek “using R for Statistics”, Sarah Stowell, chapter 10)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>brains <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="at">file =</span> <span class="st">"data/brains.csv"</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(brains)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: right;">Pair</th>
<th style="text-align: right;">Twin1</th>
<th style="text-align: right;">Twin2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">1005</td>
<td style="text-align: right;">963</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">1035</td>
<td style="text-align: right;">1027</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">1281</td>
<td style="text-align: right;">1272</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">1051</td>
<td style="text-align: right;">1079</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">1034</td>
<td style="text-align: right;">1070</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: right;">1079</td>
<td style="text-align: right;">1173</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: right;">1104</td>
<td style="text-align: right;">1067</td>
</tr>
<tr class="even">
<td style="text-align: right;">8</td>
<td style="text-align: right;">1439</td>
<td style="text-align: right;">1347</td>
</tr>
<tr class="odd">
<td style="text-align: right;">9</td>
<td style="text-align: right;">1029</td>
<td style="text-align: right;">1100</td>
</tr>
<tr class="even">
<td style="text-align: right;">10</td>
<td style="text-align: right;">1160</td>
<td style="text-align: right;">1204</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Toets met een t-toets of er een relatie is tussen het hersenvolume en geboortevolgorde. Ga er vanuit dat het hersenvolume normaal verdeeld is. De gegevens zijn vanzelfsprekend gepaard omdat Twin1 van een geboorte correspondeert met Twin2 van dezelfde geboorte. Een gepaarde t-toets is dus geschikt. Omdat verschillen in elke richting interessant zijn wordt een tweezijdige toets gebruikt.</p>
<p><strong>Toetsingsgrootheid</strong> : v = <span class="math inline">\(\mu_{Twin1} - \mu_{Twin2}\)</span></p>
<p><span class="math inline">\(H_0 : v = 0\)</span></p>
<p><span class="math inline">\(H_1 : v \neq 0\)</span>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(brains<span class="sc">$</span>Twin1, brains<span class="sc">$</span>Twin2, <span class="at">paired =</span> <span class="cn">TRUE</span>)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Paired t-test

data:  brains$Twin1 and brains$Twin2
t = -0.47424, df = 9, p-value = 0.6466
alternative hypothesis: true mean difference is not equal to 0
95 percent confidence interval:
 -49.04566  32.04566
sample estimates:
mean difference 
           -8.5 </code></pre>
</div>
</div>
<p>Het gemiddelde verschil in hersenvolume is -8.5, wat inhoudt dat het hersenvolume van de eerstgeborene gemiddeld 8.5 cm<sup>3</sup> minder is dan van de laatstgeborene. Het 95% betrouwbaarheidsinterval loopt van -49 to 32 cm<sup>3</sup>. De waarde van -8.5 ligt hierin.</p>
<p>De p-waarde van 0.6466 is groter dan 5%, dus de nulhypothese kan niet verworpen worden, er is dus geen bewijs dat het hersenvolume gerelateerd is aan de volgorde van geboorte.</p>
</div>
<div id="exm-ttoets-6" class="theorem example">
<p><span class="theorem-title"><strong>Voorbeeld 6.6 </strong></span>Is een afslankproduct wel effectief zoals de fabrikant beweert? Om dat na te gaan worden 25 proefpersonen gevolgd. Elk worden ze gewogen voor ze aan de kuur beginnen en erna.</p>
<p>(Inspiratiebron: <a href="https://nl.wikipedia.org/wiki/T-toets#Definitie_bij_gepaarde_steekproeven" class="uri">https://nl.wikipedia.org/wiki/T-toets#Definitie_bij_gepaarde_steekproeven</a>)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Simulatie data</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>aantal <span class="ot">=</span> <span class="dv">25</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2345</span>)</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">rnorm</span>(<span class="at">n =</span> aantal, <span class="at">mean =</span> <span class="fl">99.5</span>, <span class="at">sd =</span> <span class="fl">26.2</span>), <span class="dv">0</span>)</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">rnorm</span>(<span class="at">n =</span> aantal, <span class="at">mean =</span> <span class="fl">92.2</span>, <span class="at">sd =</span> <span class="fl">20.1</span>), <span class="dv">0</span>)</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">persoon =</span> <span class="fu">seq</span>(<span class="dv">1</span><span class="sc">:</span>aantal), </span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>                 <span class="at">begin =</span> <span class="fu">round</span>(<span class="fu">rnorm</span>(<span class="at">n =</span> aantal, <span class="at">mean =</span> <span class="fl">99.5</span>, <span class="at">sd =</span> <span class="fl">26.2</span>), <span class="dv">0</span>), </span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>                 <span class="at">eind =</span> <span class="fu">round</span>(<span class="fu">rnorm</span>(<span class="at">n =</span> aantal, <span class="at">mean =</span> <span class="fl">92.2</span>, <span class="at">sd =</span> <span class="fl">20.1</span>), <span class="dv">0</span>))</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(df<span class="sc">$</span>begin, df<span class="sc">$</span>eind, <span class="at">paired =</span> <span class="cn">TRUE</span>)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Paired t-test

data:  df$begin and df$eind
t = 0.9381, df = 24, p-value = 0.3575
alternative hypothesis: true mean difference is not equal to 0
95 percent confidence interval:
 -7.680468 20.480468
sample estimates:
mean difference 
            6.4 </code></pre>
</div>
</div>
<p>De p-waarde van 0.3575 is groter dan 5%, dus de nulhypothese kan niet verworpen worden, er is dus geen bewijs dat het afslankproduct effectief is.</p>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Gekopieerd!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Gekopieerd!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
    var links = window.document.querySelectorAll('a:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
          // target, if specified
          link.setAttribute("target", "_blank");
          // default icon
          link.classList.add("external");
      }
    }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./z-toets.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Z-Toets</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./f-toets.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">F-Toets</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>