<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="nl" xml:lang="nl"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.280">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Statistiek met R - 4&nbsp; Toetsen</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./z-toets.html" rel="next">
<link href="./variabelen.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "Geen resultaten",
    "search-matching-documents-text": "Gevonden documenten",
    "search-copy-link-title": "Kopieer link om te zoeken",
    "search-hide-matches-text": "Extra overeenkomsten verbergen",
    "search-more-match-text": "meer overeenkomst in dit document",
    "search-more-matches-text": "meer overeenkomsten in dit document",
    "search-clear-button-title": "Wissen",
    "search-detached-cancel-button-title": "Annuleren",
    "search-submit-button-title": "Verzenden"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Toetsen</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Statistiek met R</a> 
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Inleiding</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./kansrekenen.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Kansrekening</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./kansverdelingen.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Kansverdelingen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./variabelen.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Variabelen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./toetsen.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Toetsen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./z-toets.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Z-Toets</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./t-toets.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">t-toets</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./f-toets.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">F-Toets</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chikwadraat.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Chi-Kwadraat toets</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./driehoekstest.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Driehoekstest</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./likelihood.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Maximum Likelihood</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./eda.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Exploratieve Data Analyse (EDA)</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./datasplit.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Data splitsen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./kde.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Kernel Density Estimation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./referenties.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Referenties</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">Bijlagen</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./normale-verdeling.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Normale verdeling</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Inhoudsopgave</h2>
   
  <ul>
  <li><a href="#sec-toetsen-hypothesen" id="toc-sec-toetsen-hypothesen" class="nav-link active" data-scroll-target="#sec-toetsen-hypothesen"><span class="toc-section-number">4.1</span>  Hypothesen</a></li>
  <li><a href="#sec-toetsen-toetsingsgrootheid" id="toc-sec-toetsen-toetsingsgrootheid" class="nav-link" data-scroll-target="#sec-toetsen-toetsingsgrootheid"><span class="toc-section-number">4.2</span>  Toetsingsgrootheid</a></li>
  <li><a href="#sec-toetsen-kansverdeling" id="toc-sec-toetsen-kansverdeling" class="nav-link" data-scroll-target="#sec-toetsen-kansverdeling"><span class="toc-section-number">4.3</span>  Kansverdeling toetsingsgrootheid onder <span class="math inline">\(H_0\)</span></a></li>
  <li><a href="#sec-toetsen-steekproefuitkomst" id="toc-sec-toetsen-steekproefuitkomst" class="nav-link" data-scroll-target="#sec-toetsen-steekproefuitkomst"><span class="toc-section-number">4.4</span>  Steekproefuitkomst</a></li>
  <li><a href="#sec-toetsen-kritiekgebied" id="toc-sec-toetsen-kritiekgebied" class="nav-link" data-scroll-target="#sec-toetsen-kritiekgebied"><span class="toc-section-number">4.5</span>  Kritiek gebied</a></li>
  <li><a href="#sec-toetsen-pwaarde" id="toc-sec-toetsen-pwaarde" class="nav-link" data-scroll-target="#sec-toetsen-pwaarde"><span class="toc-section-number">4.6</span>  p-waarde</a></li>
  <li><a href="#sec-toetsen-spa" id="toc-sec-toetsen-spa" class="nav-link" data-scroll-target="#sec-toetsen-spa"><span class="toc-section-number">4.7</span>  Systematische Probleem Aanpak (SPA)</a></li>
  <li><a href="#sec-toetsen-soorten" id="toc-sec-toetsen-soorten" class="nav-link" data-scroll-target="#sec-toetsen-soorten"><span class="toc-section-number">4.8</span>  Soorten statistische toetsen</a>
  <ul class="collapse">
  <li><a href="#sec-toetsen-verschil" id="toc-sec-toetsen-verschil" class="nav-link" data-scroll-target="#sec-toetsen-verschil"><span class="toc-section-number">4.8.1</span>  Verschiltoetsen</a></li>
  <li><a href="#sec-toetsen-samenhang" id="toc-sec-toetsen-samenhang" class="nav-link" data-scroll-target="#sec-toetsen-samenhang"><span class="toc-section-number">4.8.2</span>  Samenhang tussen twee kenmerken</a></li>
  </ul></li>
  <li><a href="#sec-toetsen-oefeningen" id="toc-sec-toetsen-oefeningen" class="nav-link" data-scroll-target="#sec-toetsen-oefeningen"><span class="toc-section-number">4.9</span>  Oefeningen</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-toetsen" class="quarto-section-identifier d-none d-lg-block"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Toetsen</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>Bij een experiment waarin het toeval een rol speelt weet je van te voren niet wat de uitkomst van een waar te nemen grootheid is. Wel kunnen meestal de <em>mogelijke</em> uitkomsten worden aangegeven, denk aan een worp met een dobbelsteen. De <em>kansverdeling</em> geeft aan hoe de kansen verdeeld zijn. De waar te nemen grootheid wordt ook wel <em>stochastische variabele</em>, <em>stochastische grootheid</em>, <em>toevalsvariabele</em>, <em>kansvariabele</em> of <em>stochast</em> genoemd.</p>
<section id="sec-toetsen-hypothesen" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="sec-toetsen-hypothesen"><span class="header-section-number">4.1</span> Hypothesen</h2>
<p>In de statistische toetsingstheorie worden <em>hypothesen</em> (veronderstellingen) gemaakt over de kansverdeling van de kansvariabele. Het doel van een statistische toets is: door middel van een steekproef een of ander effect aan te tonen. De gevolgde methode is dat aangenomen wordt dat het effect niet bestaat. Dit wordt de <em>nulhypothese</em> genoemd, aangeduid met <span class="math inline">\(H_0\)</span>. Op basis van de gevonden resultaten wordt bekeken of deze veronderstelling stand kan houden.</p>
<p>Als <em>alternatieve hypothese</em>, aangeduid met <span class="math inline">\(H_1\)</span>, ga je uit van de veronderstelling dat het gezochte effect wel bestaat. Het is deze alternatieve hypothese die men tracht te “bewijzen”. Hoewel de alternatieve hypothese vaak het complement is van de nulhypothese (en dan eigenlijk overbodig), hoeft dit niet noodzakelijkerwijs het geval te zijn.</p>
</section>
<section id="sec-toetsen-toetsingsgrootheid" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="sec-toetsen-toetsingsgrootheid"><span class="header-section-number">4.2</span> Toetsingsgrootheid</h2>
<p>Na het formuleren van de hypothesen formuleer je een <em>toetsingsgrootheid</em>. Deze moet de informatie uit de steekproef samenvatten in een getal dat als maatstaf kan functioneren om de nulhypothese al dan niet te verwerpen. Veel gebruikte toetsingsgrootheden zijn: (steekproef)gemiddelde, (steekproef)fractie en (steekproef)variantie.</p>
</section>
<section id="sec-toetsen-kansverdeling" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="sec-toetsen-kansverdeling"><span class="header-section-number">4.3</span> Kansverdeling toetsingsgrootheid onder <span class="math inline">\(H_0\)</span></h2>
<p>Door uit te gaan van de nulhypothese is het mogelijk om een kansverdeling van de te onderzoeken variabele op te stellen. Hierdoor kun je uitspraken doen over de mogelijke waarden van de steekproefresultaten.</p>
</section>
<section id="sec-toetsen-steekproefuitkomst" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="sec-toetsen-steekproefuitkomst"><span class="header-section-number">4.4</span> Steekproefuitkomst</h2>
<p>Bereken de waarde van de toetsingsgrootheid uit de steekproefresultaten</p>
</section>
<section id="sec-toetsen-kritiekgebied" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="sec-toetsen-kritiekgebied"><span class="header-section-number">4.5</span> Kritiek gebied</h2>
<p>Het gaat er nu om dat voor de toetsingsgrootheid aangegeven wordt welke waarden als aannemelijk beschouwd kunnen worden en welke waarden als uitzonderlijk, gegeven <span class="math inline">\(H_0\)</span>. Als de steekproef een uitzonderlijke uitkomst oplevert, dan wijst dat er op dat de geldigheid van <span class="math inline">\(H_0\)</span> in twijfel moet worden getrokken. Dan wordt <span class="math inline">\(H_0\)</span> verworpen ten gunste van <span class="math inline">\(H_1\)</span>. De verzameling uitkomsten kunnen in twee gebieden verdeeld worden:</p>
<ul>
<li><em>Acceptatiegebied</em>, de uitkomsten die niet leiden toe verwerping van <span class="math inline">\(H_0\)</span>.</li>
<li><em>Kritieke gebied Z</em>, de uitkomsten die leiden tot verwerping van <span class="math inline">\(H_0\)</span>.</li>
</ul>
<p>Als criterium om tot een dergelijke verdeling te komen wordt de kans genomen dat de nulhypothese ten onrechte verworpen wordt. Dit wordt ook wel de <em>onbetrouwbaarheid</em> of <em>fout van de eerste soort</em> genoemd en aangeduid met <span class="math inline">\(\alpha\)</span>. De waarde van <span class="math inline">\(\alpha\)</span> wordt meestal vooraf gekozen.</p>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Opmerking
</div>
</div>
<div class="callout-body-container callout-body">
<p>Het kritieke gebied volgt uit de kansverdeling van de toetsingsgrootheid en kan dus bepaald worden zonder over steekproefresultaten te beschikken. het steekproefresultaat wordt in feite achteraf vergeleken met het kritieke gebied.</p>
</div>
</div>
</section>
<section id="sec-toetsen-pwaarde" class="level2" data-number="4.6">
<h2 data-number="4.6" class="anchored" data-anchor-id="sec-toetsen-pwaarde"><span class="header-section-number">4.6</span> p-waarde</h2>
<p>Als alternatief voor de bepaling van het kritieke gebied kan ook de <em>overschrijdingskans</em> bepaald worden van de gevonden waarde van de toetsingsgrootheid. Deze overschrijdingskans wordt meestal de <em>p-waarde</em> genoemd. Hoe kleiner de p-waarde, des te extremer de uitkomst.</p>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Opmerking
</div>
</div>
<div class="callout-body-container callout-body">
<p>Om de p-waarde te bepalen moet je over de steekproefresultaten beschikken.</p>
</div>
</div>
</section>
<section id="sec-toetsen-spa" class="level2" data-number="4.7">
<h2 data-number="4.7" class="anchored" data-anchor-id="sec-toetsen-spa"><span class="header-section-number">4.7</span> Systematische Probleem Aanpak (SPA)</h2>
<ol type="1">
<li>Formuleer <span class="math inline">\(H_0\)</span> en <span class="math inline">\(H_1\)</span> (let op de één/twee-zijdigheid!)</li>
<li>Kies de onbetrouwbaarheid (<span class="math inline">\(\alpha\)</span>)</li>
<li>Formuleer de toetsingsgrootheid (op grond van de waarde van welke variabele wordt een besluit genomen?)</li>
<li>Bepaal de kansverdeling van de toetsingsgrootheid onder de aanname dat <span class="math inline">\(H_0\)</span> waar is.!</li>
<li>Methode 1
<ol type="a">
<li>Bepaal het <strong>kritieke gebied</strong>. Dit zijn de verzameling uitkomsten die leiden tot verwerping van <span class="math inline">\(H_0\)</span>.</li>
<li>Kijk of de waarde van de toetsingsgrootheid in de steekproef wel/niet kritiek is.</li>
</ol></li>
<li>Methode 2
<ol type="a">
<li>Bereken de <strong>overschrijdingskans (p-waarde)</strong> bij de steekproefwaarde van de toetsingsgrootheid.</li>
<li>Wanneer de p-waarde minder is dan <span class="math inline">\(\alpha\)</span> (bij een éénzijdige toets) of <span class="math inline">\(\frac{1}{2} \alpha\)</span> (bij een tweezijdige toets) wordt <span class="math inline">\(H_0\)</span> verworpen.</li>
</ol></li>
<li>Beslis welke hypothese wordt aanvaard en vertaal de beslissing terug naar de werkelijkheid.</li>
</ol>
<div class="callout-tip callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>Het is aan te raden om een schets van de verdeling te maken en hierin <span class="math inline">\(\alpha\)</span> en het kritieke gebied en/of p-waarde aan te geven.</p>
</div>
</div>
</section>
<section id="sec-toetsen-soorten" class="level2" data-number="4.8">
<h2 data-number="4.8" class="anchored" data-anchor-id="sec-toetsen-soorten"><span class="header-section-number">4.8</span> Soorten statistische toetsen</h2>
<p>Om te bepalen welke toets je het beste kunt gebruiken moet je het volgende weten:</p>
<ul>
<li>Het aantal variabelen (één, twee of meer) waarmee je een analyse wilt uitvoeren</li>
<li>Het meetniveau of gegevenstype van de te onderzoeken variabelen</li>
<li>Zijn de waarnemingen onafhankelijk of gepaard.</li>
</ul>
<section id="sec-toetsen-verschil" class="level3" data-number="4.8.1">
<h3 data-number="4.8.1" class="anchored" data-anchor-id="sec-toetsen-verschil"><span class="header-section-number">4.8.1</span> Verschiltoetsen</h3>
<p><strong>Verschil van één kenmerk tussen twee groepen</strong></p>
<p>Hierbij onderzoek je of één bepaald kenmerk verschillend is voor twee groepen. Bijvoorbeeld een onderzoek naar het verschil in de gemiddelde lengte bij mannen en vrouwen. De waarnemingen zijn dan onafhankelijk.</p>
<table class="table">
<thead>
<tr class="header">
<th>afhankelijke variabele</th>
<th>toets</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>nominaal</td>
<td>chikwadraat</td>
</tr>
<tr class="even">
<td>ordinaal</td>
<td>Mann-Whitney</td>
</tr>
<tr class="odd">
<td>interval/ratio</td>
<td>t</td>
</tr>
</tbody>
</table>
<p><strong>Verschil tussen twee kenmerken binnen één groep</strong></p>
<p>Bijvoorbeeld of er binnen een bepaalde groep personen verschil is tussen de linker schoenmaat en de rechter schoenmaat. De waarnemingen zijn dan gepaard.</p>
<table class="table">
<thead>
<tr class="header">
<th>variabelen</th>
<th>toets</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>nominaal</td>
<td>chikwadraat</td>
</tr>
<tr class="even">
<td>ordinaal</td>
<td>Wilcoxon</td>
</tr>
<tr class="odd">
<td>interval/ratio</td>
<td>t</td>
</tr>
</tbody>
</table>
</section>
<section id="sec-toetsen-samenhang" class="level3" data-number="4.8.2">
<h3 data-number="4.8.2" class="anchored" data-anchor-id="sec-toetsen-samenhang"><span class="header-section-number">4.8.2</span> Samenhang tussen twee kenmerken</h3>
<p>Bijvoorbeeld of bij een groep studenten de hoogte van het behaalde cijfer voor een tentamen afhangt van het aantal uren studietijd.</p>
<table class="table">
<thead>
<tr class="header">
<th>variabele 1 / 2</th>
<th>ordinaal</th>
<th>interval/ratio</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>ordinaal</td>
<td>Spearman rang</td>
<td></td>
</tr>
<tr class="even">
<td>interval/ratio</td>
<td></td>
<td>Pearson product</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="sec-toetsen-oefeningen" class="level2" data-number="4.9">
<h2 data-number="4.9" class="anchored" data-anchor-id="sec-toetsen-oefeningen"><span class="header-section-number">4.9</span> Oefeningen</h2>
<div id="exr-toetsen-oef-muntstuk" class="theorem exercise">
<p><span class="theorem-title"><strong>Oefening 4.1 </strong></span><strong>Muntstuk</strong></p>
<p>(Bron: boek Buijs, hfst. 9, voorbeeld 1a, 2a, 4)</p>
<p>Van een munstuk moet gecontroleerd worden of deze ‘zuiver’ is. Voor deze controle worden 100 worpen met dit muntstuk uitgevoerd. Er verschijnt 64 keer kop boven. Is deze munt zuiver?</p>
<p>De hypothesen worden als volgt geformuleerd:</p>
<p><span class="math inline">\(H_0: P(kop) = \pi = \frac{1}{2}\)</span> (munt is zuiver)</p>
<p><span class="math inline">\(H_1: P(kop) = \pi \neq \frac{1}{2}\)</span> (Dit is dus een tweezijdige toetsing)</p>
<p><strong>Toetsingsgrootheid</strong> <span class="math inline">\(k\)</span>: het aantal keren ‘kop’</p>
<p>De kansvariabele <span class="math inline">\(\underline{k} \sim Bin(n=100 , \pi = \frac{1}{2})\)</span></p>
<p>Het kritieke gebied is tweezijdig, aan beide kanten een gebied van 2.5%. We zoeken twee grenswaarden L(inks) en R(echts) waarvoor geldt:</p>
<p><span class="math inline">\(P(\underline{k} \lt L) \lt 0.025\)</span> en <span class="math inline">\(P(\underline{k} \gt R) \lt 0.025\)</span> en <span class="math inline">\(P(L \le \underline{k} \le R) \ge 0.975\)</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qbinom</span>(<span class="fl">0.025</span>, <span class="dv">100</span>, <span class="fl">0.5</span>)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 40</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pbinom</span>(<span class="dv">40</span>, <span class="dv">100</span>, <span class="fl">0.5</span>)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.02844397</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pbinom</span>(<span class="dv">39</span>, <span class="dv">100</span>, <span class="fl">0.5</span>)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0176001</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qbinom</span>(<span class="fl">0.975</span>, <span class="dv">100</span>, <span class="fl">0.5</span>)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 60</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pbinom</span>(<span class="dv">60</span>, <span class="dv">100</span>, <span class="fl">0.5</span>)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9823999</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pbinom</span>(<span class="dv">59</span>, <span class="dv">100</span>, <span class="fl">0.5</span>)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.971556</code></pre>
</div>
</div>
<p><strong>kritiek gebied</strong></p>
<p>Het kritieke gebied: <span class="math inline">\(Z = \{ k \mid k \le 39 \: of \: k \ge 60 \}\)</span></p>
<p>De gevonden waarde bedraagt 64, deze ligt in <span class="math inline">\(Z\)</span>, dus <span class="math inline">\(H_0\)</span> verwerpen, het gebruikte muntstuk is niet zuiver.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Grafiek tekenen</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">100</span>, <span class="at">by =</span> <span class="dv">1</span>)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">dbinom</span>(x, <span class="dv">100</span>, <span class="fl">0.5</span>)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(x, y, <span class="at">type =</span> <span class="st">"l"</span>)</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> <span class="dv">60</span>)</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> <span class="dv">39</span>)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="toetsen_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="576"></p>
</div>
</div>
</div>
<div id="exr-toetsen-oef-productieproces" class="theorem exercise">
<p><span class="theorem-title"><strong>Oefening 4.2 </strong></span><strong>Productieproces</strong></p>
<p>(Bron: boek Buijs, hfst. 9, voorbeeld 1b, 2b, 5)</p>
<p>Volgens een fabrikant levert zijn productieproces hoogstens 20% exemplaren van mindere kwaliteit op. Bij een steekproef worden 20 exemplaren gecontroleerd waarvan er 6 van mindere kwaliteit zijn.</p>
<p>De hypothesen worden als volgt geformuleerd:</p>
<p><span class="math inline">\(H_0: \pi \le 0.20\)</span></p>
<p><span class="math inline">\(H_1: \pi \gt 0.20\)</span> (Dit is dus een rechts eenzijdige toetsing)</p>
<p><strong>Toetsingsgrootheid</strong> <span class="math inline">\(k\)</span>: het aantal exemplaren van mindere kwaliteit</p>
<p>De kansvariabele <span class="math inline">\(k \sim Bin(n=20 , \pi = 0.20)\)</span></p>
<p><strong>kritiek gebied</strong></p>
<p>We zoeken nu de grenswaarde G waarvoor geldt <span class="math inline">\(P(k \le G) \ge 0.95\)</span> en <span class="math inline">\(P(k \gt G) \lt 0.05\)</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qbinom</span>(<span class="fl">0.95</span>, <span class="dv">20</span>, <span class="fl">0.2</span>)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 7</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pbinom</span>(<span class="dv">7</span>, <span class="dv">20</span>, <span class="fl">0.2</span>)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9678573</code></pre>
</div>
</div>
<p>De grenswaarde <span class="math inline">\(c = 7\)</span>, dus het kritieke gebied: <span class="math inline">\(Z = \{ k \mid k \ge 8 \}\)</span></p>
<p>Het gevonden aantal 6 zit niet in het kritieke gebied, <span class="math inline">\(H_0\)</span> wordt niet verworpen, de fabrikant kan gelijk hebben.</p>
</div>
<div id="exr-toetsen-oef-productgewicht" class="theorem exercise">
<p><span class="theorem-title"><strong>Oefening 4.3 </strong></span><strong>Productgewicht</strong></p>
<p>(Bron: boek Buijs, hfst. 9, voorbeeld 1c, 2c, 3, 9)</p>
<p>Een fabrikant garandeert dat het afgeleverde gewicht van een product minstens 1000 gram per verpakking bedraagt. Bij een steekproef worden 100 verpakkingen onderzocht, waarvan het gemiddelde gewicht 996.5 gram is. Ga er van uit dat het verpakkingsgewicht normaal verdeeld is met <span class="math inline">\(\sigma = 25\)</span>. Onderzoek de bewering van de fabrikant met <span class="math inline">\(\alpha = 0.01\)</span></p>
<p>De hypothesen worden als volgt geformuleerd:</p>
<p><span class="math inline">\(H_0: \mu \ge 1000\)</span></p>
<p><span class="math inline">\(H_1: \mu \lt 1000\)</span> (Dit is dus een links eenzijdige toetsing)</p>
<p><strong>Toetsingsgrootheid</strong> <span class="math inline">\(\bar{x}\)</span> : het steekproefgemiddelde</p>
<p>De kansvariabele <span class="math inline">\(\bar{x} \sim N(\mu = 1000 , \sigma = \frac{25}{\sqrt{100}} = 2.5)\)</span></p>
<p>We zoeken nu de grenswaarde c waarvoor geldt <span class="math inline">\(P(\bar{x} &lt; c) \lt 0.01\)</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="fl">0.01</span>, <span class="dv">1000</span>, <span class="fl">2.5</span>)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 994.1841</code></pre>
</div>
</div>
<p><strong>kritiek gebied</strong></p>
<p>Het kritieke gebied: <span class="math inline">\(Z = \{ \bar{x} \mid \bar{x} \lt 994.1841 \}\)</span></p>
<p>Het gevonden steekproefgemiddelde is 996.5, deze ligt niet in <span class="math inline">\(Z\)</span>, dus <span class="math inline">\(H_0\)</span> wordt niet verworpen, dus de fabrikant kan gelijk hebben.</p>
<p><strong>p-waarde</strong></p>
<p>Bereken de overschrijdingskans van het gevonden gemiddelde 996.5.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="fl">996.5</span>, <span class="at">mean =</span> <span class="dv">1000</span>, <span class="at">sd =</span> <span class="fl">2.5</span>)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.08075666</code></pre>
</div>
</div>
<p>De overschrijdingskans is groter dan 0.01 dus wordt <span class="math inline">\(H_0\)</span> niet verworpen.</p>
</div>
<div id="exr-toetsen-oef-montagetijden" class="theorem exercise">
<p><span class="theorem-title"><strong>Oefening 4.4 </strong></span><strong>Montagetijden</strong></p>
<p>(Bron: boek Buijs, hfst. 9, voorbeeld 6, 8)</p>
<p>De montagetijden zijn normaal verdeeld met <span class="math inline">\(\mu\)</span> = 300 sec en <span class="math inline">\(\sigma\)</span> = 15 sec.&nbsp;Bij een steekproef van 25 waarnemingen werd een gemiddelde montagetijd van 292 sec.&nbsp;gevonden. Wijkt deze significant af van de verdeling? Toets met <span class="math inline">\(\alpha\)</span> = 0.05.</p>
<p>De hypothesen worden als volgt geformuleerd:</p>
<p><span class="math inline">\(H_0: \mu = 300\)</span></p>
<p><span class="math inline">\(H_1: \mu \neq 300\)</span> (Dit is dus een tweezijdige toetsing)</p>
<p><strong>Toetsingsgrootheid</strong> <span class="math inline">\(\bar{x}\)</span> : het steekproefgemiddelde</p>
<p>De kansvariabele <span class="math inline">\(\bar{x} \sim N(\mu = 300 , \sigma = \frac{15}{\sqrt{25}} = 3)\)</span></p>
<p><strong>kritiek gebied</strong></p>
<p>Het kritieke gebied is tweezijdig, aan beide kanten een gebied van 2.5%. We zoeken twee grenswaarden L en R waarvoor geldt:</p>
<p><span class="math inline">\(P(\bar{x} \lt L) \lt 0.025\)</span> en <span class="math inline">\(P(\bar{x} \gt R) \lt 0.025\)</span> en <span class="math inline">\(P(L \le \bar{x} \le R) \ge 0.975\)</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="fl">0.025</span>, <span class="dv">300</span>, <span class="dv">3</span>)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 294.1201</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="fl">0.975</span>, <span class="dv">300</span>, <span class="dv">3</span>)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 305.8799</code></pre>
</div>
</div>
<p>Kritieke gebied: <span class="math inline">\(Z = \{ \bar{x} \mid \bar{x} \le 294.12 \: of \: \bar{x} \ge 305.8799 \}\)</span></p>
<p>Het gevonden steekproefgemiddelde is 292, deze ligt in Z, dus <span class="math inline">\(H_0\)</span> wordt verworpen, dus de gemiddelde montagetijd wijkt af van <span class="math inline">\(\mu\)</span> = 300 sec.</p>
</div>
<div id="exr-toetsen-oef-geneesmiddel" class="theorem exercise">
<p><span class="theorem-title"><strong>Oefening 4.5 </strong></span><strong>Geneesmiddel</strong></p>
<p>(Bron: boek Buijs, hfst. 9, voorbeeld 7)</p>
<p>Een geneesmiddel zou in 99% van de gevallen doeltreffend zijn. Bij een steekproef van 200 proefpersonen was het in 8 gevallen geen succes. Toets of de fabrikant gelijk kan hebben met <span class="math inline">\(\alpha\)</span> = 0.01.</p>
<p>Minstens 99% succesvol kan ook geformuleerd worden als hoogstens 1% niet werkzaam.</p>
<p>De hypothesen worden als volgt geformuleerd (<span class="math inline">\(\pi\)</span> is de kans op een mislukking:</p>
<p><span class="math inline">\(H_0: \pi \le 0.01\)</span></p>
<p><span class="math inline">\(H_1: \pi \gt 0.01\)</span> (Dit is dus een rechts eenzijdige toetsing)</p>
<p><strong>Toetsingsgrootheid</strong> <span class="math inline">\(\underline{k}\)</span>: het aantal mislukkingen</p>
<p>De kansvariabele <span class="math inline">\(\underline{k} \sim Bin(n=200 , \pi = 0.01)\)</span></p>
<p>Dus <span class="math inline">\(E(\underline{k}) = n*\pi = 200*0.01 =2\)</span> en <span class="math inline">\(var(\underline{k}) = n*\pi*(1-\pi) = 200*0.01*0.99 = 1.98\)</span></p>
<p>Omdat n groot is en <span class="math inline">\(\pi\)</span> zeer klein mag de binomiale verdeling benaderd wordeen door een Poissonverdeling met <span class="math inline">\(\mu\)</span> = 2.</p>
<p><span class="math inline">\(\underline{k} \sim Poisson(\mu = 2)\)</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dpois</span>(<span class="dv">8</span>,<span class="dv">2</span>)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0008592716</code></pre>
</div>
</div>
<p>Deze kans is veel kleiner dan <span class="math inline">\(\alpha\)</span>, dus <span class="math inline">\(H_0\)</span> verwerpen, dus de bewering van de fabrikant klopt niet.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qpois</span>(<span class="fl">0.99</span>, <span class="dv">2</span>)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6</code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dpois</span>(<span class="dv">7</span>, <span class="dv">2</span>)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.003437087</code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dpois</span>(<span class="dv">6</span>, <span class="dv">2</span>)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0120298</code></pre>
</div>
</div>
<p>Kritieke gebied: <span class="math inline">\(Z = \{7,8,9,...\}\)</span> want <span class="math inline">\(P(k \ge 7) \lt 0.01\)</span> terwijl <span class="math inline">\(P(k \ge 6) \gt 0.01\)</span></p>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Gekopieerd!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Gekopieerd!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
    var links = window.document.querySelectorAll('a:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
          // target, if specified
          link.setAttribute("target", "_blank");
          // default icon
          link.classList.add("external");
      }
    }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./variabelen.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Variabelen</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./z-toets.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Z-Toets</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>